- .github/workflows/docker.yml
- docker/Dockerfile.firedrake
Closes #28.
Currently we are basing the Docker build on Firedrake as of February. This needs updating.
> Update Docker build

- .github/workflows/docker.yml
- .github/workflows/docker_firedrake.yml
- .github/workflows/docker_petsc.yml
- docker/Dockerfile.firedrake
- docker/Dockerfile.petsc
- docker/Makefile
- install/petsc_reconfigure_options.txt
Closes #39.
Rather than reconfiguring and rebuilding Firedrake's PETSc build, if we just build it ourselves then we can more easily handle external packages and have more control.
I *think* this PR includes a fix for the Eigen linking issue but let's see. (Internet isn't good enough to check by installing locally.)
> Add PETSc Docker build

- .github/workflows/reusable_citation_check.yml
- .github/workflows/reusable_test_suite.yml
Closes #45.
After this is merged I will change `citation_check.yml` in Animate/Goalie/Movement to be:
```
name: 'Citation Check'
on:
push:
branches:
- main
paths:
- '**/*.cff'
pull_request:
paths:
- '**/*.cff'
workflow_dispatch:
jobs:
citation_check:
uses: mesh-adaptation/mesh-adaptation-docs/.github/workflows/citation_check.yml@main
```
and `test_suite.yml` in Animate will be:
```
name: 'Run Animate Test Suite'
on:
push:
branches:
- main
pull_request:
schedule:
- cron: '0 1 * * 0'
jobs:
test_suite:
uses: mesh-adaptation/mesh-adaptation-docs/.github/workflows/test_suite.yml@main
with:
install-command: 'python -m pip uninstall -y animate && python -m pip install -e .'
test-command: |
export GITHUB_ACTIONS_TEST_RUN=1
python $(which firedrake-clean)
export …
```
> #45: Add reusable workflows

- docs/Makefile
- docs/source/conf.py
- docs/source/index.rst
Closes https://github.com/mesh-adaptation/UM2N/issues/12.
This PR adds UM2N to the mesh-adaptation webpage repo so that users will be able to view the API documentation once the webpage gets updated.
> Add UM2N API documentation to webpage

- .github/workflows/docker_firedrake-parmmg.yml
- .github/workflows/docker_petsc-parmmg.yml
- .github/workflows/reusable_docker_build.yml
Closes #55. Closes #56.
I also replaced using `changed-files` with the inbuilt `paths` syntax. I think `changed-files` is great when we want some fine-grained control, but I think it is an overkill when we just use it to control workflow triggering. 
With this PR, the following triggers `docker_petsc-parmmg.yml` to run:
1. `.github/workflows/docker_petsc-parmmg.yml` or `docker/Dockerfile.petsc` change in a PR (doesn't push to ghcr)
2. `.github/workflows/docker_petsc-parmmg.yml` or `docker/Dockerfile.petsc` change on the main branch (pushes to ghcr)
3.  Scheduled at 1AM every Saturday
and the following triggers `docker_firedrake-parmmg.yml` to run:
1. `.github/workflows/docker_firedrake-parmmg.yml` or `docker/Dockerfile.firedrake` change in a PR (doesn't push to ghcr)
2. …
> Update when Docker build and push are triggered

- docs/source/goalie/index.rst
Linked to https://github.com/mesh-adaptation/goalie/pull/112 and https://github.com/mesh-adaptation/goalie/issues/28
Adds unsteady, goal-oriented demo from Goalie to documentation.
> Link burgers goal-oriented demo to docs

- .github/workflows/reusable_test_suite.yml
Closes #66.
Required for the completion of https://github.com/mesh-adaptation/UM2N/pull/59.
Note that the option defaults to `firedrake-parmmg` so that we only need to provide this for the UM2N test suite.
> Allow switching Docker image in reusable test workflow

- .github/workflows/docker_firedrake-um2n.yml
- docker/Dockerfile.firedrake-um2n
Related to #13. Cuts down the size of UM2N Docker image by about 4GB.
> In UM2N Dockerfile use firedrake-parmmg as base

- .github/workflows/build_docs.yml
Now that #88 made firedrake-um2n use firedrake-parmmg as base, we can use firedrake-um2n container to build docs.
And I think that just `git pull` is enough to get the latest changes to our packages, right? Since they're installed in editable mode (`pip install -e`)
> Use UM2N container in build_docs.yml

- .github/workflows/reusable_test_suite.yml
Related PRs:
---
This PR simplifies the `reusable_test_suite.yml` workflow:
- Not using the `changed-files` action; instead, the triggers are to be set in the Animate/Goalie/Movement/UM2N workflows using the `paths` syntax
- The `build` directory doesn't exist so `rm -rf build` does nothing (I guess this was a copy-paste error from the docs build)
- Not unnecessarily installing python with `actions/setup-python@v2`
- Not uninstalling and installing Animate/Goalie/Movement/UM2N again since `actions/checkout@v4` fetches the repository at the state of the commit that triggered the workflow, so it is always up to date
- In the "Run tests" step we have so far passed commands here from other repos, where I think `export GITHUB_ACTIONS_TEST_RUN=1` is unnecessary (not used anywhere?)
And one …
> Simplify reusable test workflow

- docs/source/conf.py
Closes #71.
Also tidied up `conf.py` by grouping up options in the `autodoc_default_options` dictionary.
> Document all members

- docs/source/index.rst
Closes #43.
Will duplicate this to https://github.com/mesh-adaptation/mesh-adaptation.github.io after it gets merged.
@jwallwork23 currently we only have Discussions open on Goalie. If you agree I'd also open them on other repos.
> Mention Slack channels on the website

- .github/workflows/reusable_docker_build.yml
- .github/workflows/reusable_test_suite.yml
- docker/Dockerfile.firedrake-parmmg
Firedrake is now installable via `pip`, with `firedrake-install` now giving a `FutureWarning`. For an overview of changes on Firedrake side, see https://github.com/firedrakeproject/firedrake/pull/4011. This PR updates the `firedrake-parmmg` image and `reusable_test_suite.yml` workflows to conform to those changes, as described below.
General:
- The `firedrake-parmmg` image is now only 2.4GB and the build time is almost twice as fast (25 min faster)!
- Mesh adaptation repos are now cloned to the home directory (they used to be under `/home/firedrake/firedrake/src`). Firedrake made this change in their containers too so I am just following their structure.
- It is no longer necessary to create a virtual environment, so I don't create one (to be consistent with Firedrake's containers again). …
> Updates to `firedrake-parmmg` and testing due to Firedrake's new `pip install`

- .github/workflows/publish_wiki.yml
- .github/workflows/reusable_test_suite.yml
Fixes for issues identified in #117:
- template injection (see https://woodruffw.github.io/zizmor/audits/#template-injection)
- excessive permissions (see https://woodruffw.github.io/zizmor/audits/#excessive-permissions) 
Edit: I completely removed the option to set the animate checkpoint directory via input to the workflow. I don't think we would want to change this from the default, so it was just overcomplicating things. So if you agree with this change, the Animate test workflow should go from this:
```
jobs:
test_suite:
uses: mesh-adaptation/docs/.github/workflows/reusable_test_suite.yml
with:
test-command: |
export ANIMATE_CHECKPOINT_DIR=$(pwd)/.checkpoints
```
to this:
```
jobs:
test_suite:
uses: mesh-adaptation/docs/.github/workflows/reusable_test_suite.yml
```
> Avoid workflow vulnerabilities

- .github/workflows/reusable_test_suite.yml
Further to #114 and discussion in https://github.com/mesh-adaptation/animate/pull/175, it actually is possible to run parallel tests with 3 processes (should be possible with 4 as well). This PR adds them.
I also accidentally deleted `${{ inputs.test-command }}` in #114 so putting this back in now.
> Run parallel tests with 3 processes in the CI

- .github/workflows/reusable_test_suite.yml
- docker/Dockerfile.firedrake-parmmg
- docker/Dockerfile.firedrake-um2n
There have been further changes to Firedrake's docker images. Previously we used `firedrake-env` as the base image, where they would install some system dependencies, set the `firedrake` user etc. But now they removed this and they use the `root` user, with packages being installed in `/opt`.
I think it's neater to keep it as it has been so far: be non-root and have packages installed in `/home/firedrake`. So this PR keeps things as they were: it just moves things from the old `firedrake-env` image to `firedrake-parmmg` and tidies things up a bit. 
The only change is that I install thetis, which I forgot to add in the previous PR.
- I tested the `firedrake-parmmg` image with with Goalie in https://github.com/mesh-adaptation/goalie/pull/299
- I tested the `firedrake-um2n` image locally and …
> Update docker images

- docker/Dockerfile.firedrake-parmmg
Fix for failing docker build today ( https://github.com/mesh-adaptation/docs/actions/runs/14326905287/job/40153996141 ).
> Update `Dockerfile.firedrake-parmmg` (firedrakeproject/petsc -> petsc/petsc)

- wiki/Installation-Instructions.md
Closes #84.
@jwallwork23 @acse-ej321 I added some more details for NVIDIA GPUs since that's what I have. Do either of you have an AMD GPU by any chance? If so, could you please test this and try to run the AMD equivalent of `nvidia-smi`? I think that should be `rocm-smi`.
> Wiki addition: how to run containers with GPUs

- wiki/Installation-Instructions.md
I think it would be good to further expand and clarify the installation instructions in the wiki:
- I added a section on how to reconfigure an existing PETSc installation. I think this is useful since I assume that many users will already have an existing installation
- I clearly separated the "local install" and "Docker" approaches and their differences. I thought that it was slightly confusing in its current state.
- I now explicitly state that the Docker image has everything pre-installed and ready to use.
- I put the section on Docker at the very end, so that it is not intertwined with the 'local installation' approach
- I simplified the 'Installing Mesh Adaptation modules' section with various minor changes (will leave comments on specific changes)
> Wiki: Clarify installation instructions; add PETSc `reconfigure` section

- docker/Dockerfile.firedrake-parmmg
Closes #131
Following https://github.com/firedrakeproject/firedrake/commit/c48cadfb503ddfcb9ff5a7ffa28605e2fc5dc95e hdf5 and others now use Ubuntu system packages, which means we have to be careful to not clobber the [CXX|C|F]OPTFLAGS suggested by firedrake-configure
Also it appears we now need to explicitly --download-metis for parmetis (which depends on it) to build.
> Fix docker build

- docker/Dockerfile.firedrake-parmmg
Closes #137
Previous changes to docker build introduced a pip constraints file to force cython < 3.1. The file was specified without a path, so that pip no longer worked in other directories.
> Absolute path for pip constraints file

- docker/Dockerfile.firedrake-parmmg
I removed this because I thought it was only needed for the petsc build which we used to build as root, but is now build as user firedrake just like firedrake itself. Turns out the CI tests actually switch back to --user=root for running the tests for some reason.
> Reinstate OMPI_ALLOW_RUN_AS_ROOT=1

- wiki/Installation-Instructions.md
When I follow the instructions for a fresh install, I get an error in configuring parmetis. The error went away when I added `--download-metis` first. The instructions already have both packages for updating an existing PETSc install.
> fix install instructions for metis

- docker/Dockerfile.firedrake-parmmg
Related to https://github.com/mesh-adaptation/animate/issues/136
As discussed in https://github.com/mesh-adaptation/animate/issues/136 the MMG3d failures (serial or serialised parallel) are due to failing "source fortification" checks in scotch which is used by mmgd3d. Scotch is known unsafe for these and they have been switched off in versions >=7.0.7 As advised in https://gitlab.com/petsc/petsc/-/issues/1762 we can switch to a v7.0.8 prerelease to deal with this.
I've tried this out here: https://github.com/mesh-adaptation/animate/pull/184 (using a docker build of this PR that I pushed somewhere else) and it indeed seems to fix all mmg3d failures.
> Switch to scotch v7.0.8a
